//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Res" +
                            "ources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string FileBrowseEditorBrowseButtonText {
            get {
                return ResourceManager.GetString("FileBrowseEditorBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected profile.
        /// </summary>
        public static string LaunchProfileMenuDeleteToolTip {
            get {
                return ResourceManager.GetString("LaunchProfileMenuDeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate selected profile.
        /// </summary>
        public static string LaunchProfileMenuDuplicateToolTip {
            get {
                return ResourceManager.GetString("LaunchProfileMenuDuplicateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string LaunchProfileMenuNewText {
            get {
                return ResourceManager.GetString("LaunchProfileMenuNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new profile.
        /// </summary>
        public static string LaunchProfileMenuNewToolTip {
            get {
                return ResourceManager.GetString("LaunchProfileMenuNewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename selected profile.
        /// </summary>
        public static string LaunchProfileMenuRenameToolTip {
            get {
                return ResourceManager.GetString("LaunchProfileMenuRenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        public static string LaunchProfileNewProfileName {
            get {
                return ResourceManager.GetString("LaunchProfileNewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading launch profiles....
        /// </summary>
        public static string LaunchProfilesWindowAsyncLoadMessage {
            get {
                return ResourceManager.GetString("LaunchProfilesWindowAsyncLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Profiles.
        /// </summary>
        public static string LaunchProfilesWindowTitleText {
            get {
                return ResourceManager.GetString("LaunchProfilesWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading properties....
        /// </summary>
        public static string ProjectPropertiesAsyncLoadMessage {
            get {
                return ResourceManager.GetString("ProjectPropertiesAsyncLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the same value across all configurations.
        /// </summary>
        public static string PropertyUseSameValueAcrossAllConfigurations {
            get {
                return ResourceManager.GetString("PropertyUseSameValueAcrossAllConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vary value by {0}.
        /// </summary>
        public static string PropertyVaryByDimension_1 {
            get {
                return ResourceManager.GetString("PropertyVaryByDimension_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search properties.
        /// </summary>
        public static string SearchTextBoxWatermarkText {
            get {
                return ResourceManager.GetString("SearchTextBoxWatermarkText", resourceCulture);
            }
        }
    }
}
